### ISSUE TITLE
Support mulit-mesh topology netcdf files

### ISSUE THREAD

**Issue by markhegnauer** [Deltares/xugrid#10]
In Delft3D-FM, output files contain multiple mesh topologies ['network1d', 'mesh1d', 'mesh2d']. Ideally, xugrid can be used to read and plot data from these output files, but now this gives an NotImplementedError.

**Comment by rhutten** [comment]
@Huite, Any idea when this issue can be picked up?

**Comment by Huite** [comment]
I'm looking at this now, just jotting down some notes. There are two parts to this issue:

* The UGRID parsing currently does not group by topology, and so it fails to separate between the different topologies that are present in a file.
* The UgridDataset, like the UgridDataArray, supports only a single topology (in the form of a Ugrid1d, Ugrid2d object).

The first issue is straightforward: create some logic which interrogates a dataset to provide variables in grouped form. These could then be instantiated into separate single-topology UgridDatasets. This runs into complications immediately, as many data variables may be wholly unrelated to any topology. It would be much cleaner to simply represent the entire file as a single dataset (part two).

Currently, the UgridDataset and UgridDataArray share a property `.ugrid`, which returns a `UgridAccessor` which contains both the xarray object and its grid object. For a UgridDataArray, it's obvious that only a single topology should be allowed. However, this is unnecessarily strict for a UgridDataset. Multiple variables (DataArrays) could support multiple topologies: they can simply be matched by dimension name. This requires separate accessors for Datasets and DataArrays, but that seems desirable anyway: many operations currently will not work on Datasets (while after separation, the dataset operations simply iterate over variables).

In a few steps:

* Split the accessors
* Create a dict of dimension => grid

The second part probably creates some additional complexity: e.g. how to variables with new topology. That one seems straightforward enough (ingest the grid as well as the data during setitem), but more complex stuff may pop up.

**Comment by Huite** [comment]
Done in [9563e83](https://github.com/Deltares/xugrid/commit/9563e83eeb93346bdae4a3ef9441a4ab3c9ebb4e)

I'll create a new PyPI and conda release.

(With some potential rough edges.)
