### ISSUE TITLE
dataset attrs are ignored upon writing

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/xugrid#111]
When writing a uds to a file, the provided attributes are overwritten by the conventions from xugrid. This might be desireable behaviour for the `Conventions` attribute (but I'd like to know more about this), but the other attrs should not be dropped in my view.

```
import xugrid as xu

uds = xu.data.adh_san_diego()
uds = uds.assign_attrs({'Conventions': 'CF-1.8 UGRID-1.0 Deltares-0.10', #TODO: add Deltares convention (was CF-1.8 UGRID-1.0)
                        'institution': 'Deltares',
                        'references': 'https://www.deltares.nl'})

file_out = 'test_conventions.nc'
uds.ugrid.to_netcdf(file_out)

uds2 = xu.open_dataset(file_out)
print(uds.attrs)
print(uds2.attrs)
```

Returns:
- {'Conventions': 'CF-1.8 UGRID-1.0 Deltares-0.10', 'institution': 'Deltares', 'references': 'https://www.deltares.nl'}
- {'Conventions': 'CF-1.8 UGRID-1.0'}

Also, should it not be CF-1.9?  [ocean_sigma_over_z_coordinate was only correct from then onwards](https://cfconventions.org/cf-conventions/cf-conventions.html#_ocean_sigma_over_z_coordinate)

**Comment by Huite** [comment]
https://github.com/Deltares/xugrid/blob/262f759abf0667da2b2278fb208ced119a0a3c06/xugrid/ugrid/ugrid2d.py#L360C7-L360C83

This is rather cutting the corner, indeed!
