### ISSUE TITLE
regridding of regular grid to unstructured grid provides flipped values on y axis

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/xugrid#157]
[We've got a user running into this issue](https://gitlab.com/deltares/imod/imod-python/-/issues/531).

_When trying to regrid an structured grid to an unstructured one, the values are flipped on the y axis._
_Original code:_

``regridder = xu.CentroidLocatorRegridder(source=riv_bot, target=uds_grid)``
``riv_bot = regridder.regrid(riv_bot)``

_It gets fixed by reversing the y axis before the regridding:_

``riv_bot = riv_bot.reindex(y=list(reversed(riv_bot.y)))``

![image](https://github.com/Deltares/xugrid/assets/9744750/03ea52bd-9260-42a7-9887-739a4a0004d8)

**Comment by Huite** [comment]
Some temporary test stuff:

```python
# %%
import xugrid as xu
import numpy as np
import xarray as xr
# %%

uda = xu.data.elevation_nl()
xmin, xmax, ymin, ymax = uda.grid.bounds
# %%
x = np.arange(xmin, xmax, 1000.0)
y = np.arange(ymin, ymax, 1000.0)
da = xr.DataArray(
    data=np.zeros((y.size, x.size)),
    coords={"y": y, "x": x, "dx": ("x", np.full(x.size, 1000.0)), "dy": ("y", np.full(y.size, 1000.0))},
    dims=["y", "x"]
)
# %%

regridder = xu.OverlapRegridder(source=uda, target=da, method="mean")
# %%
result = regridder.regrid(uda)
# %%


decreasing_y = result.isel(y=slice(None, None, -1))
regridder = xu.OverlapRegridder(source=decreasing_y, target=uda, method="mean")
new = regridder.regrid(decreasing_y)

# %%

# Structured to structured
regridder = xu.OverlapRegridder(source=decreasing_y, target=result)
new = regridder.regrid(decreasing_y)
# %%


```

Structured to structured is okay, it takes the flipping into account properly.

I'm pretty sure it's the structured -> unstructured conversion that happens that's causing the disconnect.

**Comment by Huite** [comment]
We should add a test with four equivalent datasets:

* structured increasing y
* structured decreasing y
* structured increasing y as ugrid
* structured decreasing y as ugrid

And regrid them to a single target unstructured grid / target structured grid.
All the results should be the same then.
