### ISSUE TITLE
New xarray release breaks xugrid due to changes in xarray plot utils

### ISSUE THREAD

**Issue by Huite** [Deltares/xugrid#162]
Importing xugrid with the latest xarray results in:

ImportError: cannot import name 'import_matplotlib_pyplot' from 'xarray.plot.utils

Likely a namespace or something in xarray has changed. Since these are internal methods really, we should arguably just copy them into xugrid.

**Comment by veenstrajelmer** [comment]
up to xarray 2023.8.0 they had the following function: https://github.com/pydata/xarray/blob/83c2919b27b4b2d8a01bfa380226134c71321aa0/xarray/plot/utils.py#L50-L55

This can easily be replaced by the contents: `import matplotlib.pyplot as plt`
