### ISSUE TITLE
Back and forth conversion xugrid - meshkernel does not work for spherical network

### ISSUE THREAD

**Issue by Tammo-Zijlker-Deltares** [Deltares/xugrid#177]
Loading a ugriddataset, converting to a meshkernel object (to apply transformations such as deletion with meshkernel) and converting back to a ugrid dataset does not work for spherical networks. 

This probably has to do that in conversion from ugrid to meshkernel, the sperical projection information is lost. 

Sample code:
```
# Imports
import dfm_tools as dfmt
import meshkernel as mk

# Load a model grid as UgridDataset

network = dfmt.open_partitioned_dataset(r'p:\11208614-de-370a\01_models\Humber\DFLOWFM\Models\humber_basque_modelbuilder\humber_basque_net.nc') 

#Convert the network to a meshkernel object
mk_object = network.grid.meshkernel

# Delete non-contiguous parts of the grid
mk_object.mesh2d_remove_disconnected_regions()
crs = 'EPSG:4326'


#convert to xugrid, interpolate z-values and write to netcdf
xu_grid_uds = dfmt.meshkernel_to_UgridDataset(mk=mk_object, crs=crs)
```

The error is: 

ValueError: `is_geographic` mismatch between provided grid (is_geographic=False) and provided crs (EPSG:4326, is_geographic=True)

**Comment by veenstrajelmer** [comment]
This has to do with the fact that all `Ugrid2d.meshkernel` instances are initialized as cartesian. We should support spherical networks in the xugrid to meshkernel conversion.

**Comment by Huite** [comment]
Related to: https://github.com/Deltares/xugrid/issues/52

Any code that touches lengths or areas requires an alternative implementation.

The area computation in overlap regridding is done in numba_celltree: https://github.com/Deltares/numba_celltree/blob/ab64846dc8297c20a9d445f751bfcf6c1271b39a/numba_celltree/geometry_utils.py#L77

If you want to make it fancy, it can get quite tedious: https://r-spatial.github.io/sf/articles/sf7.html
