### ISSUE TITLE
Test python 3.12 support

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/xugrid#178]
Numba currently does not support python 3.12: https://github.com/numba/numba/issues/9197

When this is fixed:
- [ ] add py312 testbank and check if all green
- [ ] update supported python versions in pyproject.toml

**Comment by Huite** [comment]
Fixed by d0b9459ed05b51e94a847fb44fe5efcaabb4f41d

numba_celltree needs to be updated in terms of its supported Python versions.

**Comment by veenstrajelmer** [comment]
The classifiers should also be updated in the pyproject.toml: https://github.com/Deltares/xugrid/blob/main/pyproject.toml#L30
