### ISSUE TITLE
Resolve `Dataset.dims` FutureWarning

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/xugrid#190]
The below code gives a FutureWarning with xarray 2023.12.0:
```
import xugrid as xu
import dfm_tools as dfmt
file_nc = dfmt.data.fm_curvedbend_map(return_filepath=True)
uds = xu.open_dataset(file_nc)
```

`"[...]\site-packages\xarray\core\utils.py:494: FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`."`

The used netcdf file is also available [on opendap](https://opendap.deltares.nl/thredds/catalog/opendap/deltares/Delft3D/netcdf_example_files/DFM_curvedbend_3D/catalog.html?dataset=varopendap/deltares/Delft3D/netcdf_example_files/DFM_curvedbend_3D/cb_3d_map.nc).

Also happens in:
`C:\DATA\xugrid\xugrid\ugrid\partitioning.py:384: FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
  chunks[dim] = (merged.dims[dim],)`

**Comment by JoerivanEngelen** [comment]
Relevant xarray issue: https://github.com/pydata/xarray/issues/8496
