### ISSUE TITLE
Migrate from PyGEOS to Shapely 2.0

### ISSUE THREAD

**Issue by JoerivanEngelen** [Deltares/xugrid#33]
[From the Shapely migration documentation:](https://shapely.readthedocs.io/en/stable/migration_pygeos.html) 

> The PyGEOS package was merged with Shapely in December 2021 and will be released as part of Shapely 2.0. No further development will take place for the PyGEOS package (except for providing up to date packages until Shapely 2.0 is released).

Migrating seems quite straightforward from the documentation.

**Comment by Huite** [comment]
Closed by 418028a7fede20b50e25b828ee3a78c429811dc7
