### ISSUE TITLE
"rasterize" vector geometry to unstructured grid and selection

### ISSUE THREAD

**Issue by Huite** [Deltares/xugrid#50]
An indirect route is rasterizing using GDAL to a raster, then using some regridding machinery.

Alternatively, we could use earcut: https://pypi.org/project/mapbox-earcut/ (ISC licensed, equivalent to MIT).
If we triangulate the polygons, they can be treated as a triangular unstructured grid. Then use the regridding machinery.

**Comment by Huite** [comment]
Other options:

* just search the nodes or centroids using shapely
* use pandamesh to turn the polygons into a mesh first, then overlap

**Comment by Huite** [comment]
Best to benchmark, probably depends on the use case, complexity of polygon, etc.

**Comment by betsyromero** [comment]
The GDAL docs on rasterize refer to "burning": https://gdal.org/programs/gdal_rasterize.html

So we could call it "burn_polygons", etc.
