### ISSUE TITLE
.ugrid.sel() does not accept dict as input

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/xugrid#58]
.ugrid.sel() does not accept dictionary as input. Raises "TypeError: Invalid indexer type: dict, allowed types: integer, float, list, numpy array, xarray DataArray". However, using dicts as input for xarray.s ds.sel() is possible.

```python
import xugrid as xu

file_nc = 'c:\\DATA\\dfm_tools_testdata\\DFM_3D_z_Grevelingen\\computations\\run01\\DFM_OUTPUT_Grevelingen-FM\\Grevelingen-FM_0003_map.nc'

uds = xu.open_dataset(file_nc)

#works: passing arguments and values to xugrid's .sel()
uds_sel = uds.ugrid.sel(x=slice(50000,55000),y=slice(None,423000))

#works: passing dict with arguments to xarray's .sel()
uds_sel = uds.sel({'time':slice('2007-11-01','2007-11-05')})

#fails: passing dict with arguments to xugrid's .sel()
uds_sel = uds.ugrid.sel({'x':slice(50000,55000),'y':slice(None,423000)})
```

**Comment by veenstrajelmer** [comment]
Workaround is to use `**` like this, which unpacks the dictionary:
`uds_sel = uds.ugrid.sel(**{'x':slice(50000,55000),'y':slice(None,423000)})`

**Comment by Huite** [comment]
There's the (copied from xarray) `either_dict_or_kwargs` function: https://github.com/Deltares/xugrid/blob/b2f9dd6498042af4ff6e10105afe41c9b72a9068/xugrid/core/utils.py#L24

**Comment by veenstrajelmer** [comment]
I do not see why I opened this issue in the first place to be honest. The original code still raises `"TypeError: Invalid indexer type: dict, allowed types: integer, float, list, numpy array, xarray DataArray"`, but the workaround works properly. The function is already not consistent with xarray since `x` and `y` are not dimensions, so maybe we can leave this like it is.
