### ISSUE TITLE
Function for periodic global grid to non-periodic 

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/xugrid#63]
Copy x=-180 nodes to x=180 and update face/edge topology.

In case of periodic grid, conversion to non-periodic is necessary for:
- rasterizing
- interpolation
- plotting
- regridding

All these features fail if there are "around the back" cells/faces

Test data is available at p:\1230882-emodnet_hrsm\GTSMv5.0\runs\reference_GTSMv4.1_wiCA_2.23.08_mf4\output_small\

Partition 0005 also goes around the back, so testing with only 1 partition is also possible.

**Comment by Huite** [comment]
For plotting: an attribute (or property or something) would be useful. In that case, there's no need to create a whole new topology: just special case it for the plotting.

**Comment by veenstrajelmer** [comment]
It is also convenient if we can rasterize the ugrid, for which you would also need an updated topology I think.

**Comment by veenstrajelmer** [comment]
Would this not be relatively easy by regridding the dataset like https://deltares.github.io/xugrid/examples/regridder_overview.html?
It might be too computationally heavy though?

**Comment by Huite** [comment]
Periodic arguably has a more general meaning that what we describe here: https://en.wikipedia.org/wiki/Periodic_boundary_conditions

> Periodic boundary conditions (PBCs) are a set of [boundary conditions](https://en.wikipedia.org/wiki/Boundary_condition) which are often chosen for approximating a large (infinite) system by using a small part called a unit cell. PBCs are often used in [computer simulations](https://en.wikipedia.org/wiki/Computer_simulation) and [mathematical models](https://en.wikipedia.org/wiki/Mathematical_model). Periodic boundary conditions (PBCs) are a set of [boundary conditions](https://en.wikipedia.org/wiki/Boundary_condition) which are often chosen for approximating a large (infinite) system by using a small part called a unit cell. PBCs are often used in [computer simulations](https://en.wikipedia.org/wiki/Computer_simulation) and [mathematical models](https://en.wikipedia.org/wiki/Mathematical_model).

The logic required to create such a grid is exactly identical to the one required for this global grid. If we have a grid which runs from x=0 to x=5, but we want a periodic simulation to simulate an infinite domain, we would similarly connect the left side to the right by substituting the rightmost face nodes with those on the left.

* `to_periodic` would substitute x=5 with x=0.
* `to_nonperiodic` would substitute the rightmost x=0 with x=5, given xmax=5.0 as an argument

I think the spherical cases can be reasonably seen as a special case where the domain is finite.

Although to properly implement it, an optional `ymax` argument should also be introduced, and xmax should be made optional as well.
