### ISSUE TITLE
Add UgridDataset.from_structured method

### ISSUE THREAD

**Issue by Huite** [Deltares/xugrid#8]
UgridDataArray already has a from_structured constructor, but doing so for every variable of a dataset means rederiving the UGRID topology every time -- so just do it once, then figure out how to add every variable.

**Comment by Huite** [comment]
Some tedious details:

* There may be multiple topologies present in a single dataset.
* These could all be converted into single UgridDataset (since it supports multiple topologies), but this requires inventing names.
* Perhaps the easiest is to add an argument mapping `{topology_name: (x_coordinate, y_coordinate)}`
* If None, this defaults to `{"mesh2d": ("x", "y")}` (which somewhat bakes in a 2D structured topology, but I guess 3D structured topology is really far away enough...). This ensures `uds = xu.UgridDataset.from_structured(ds)` works for a lot of common cases.
* All non-associated variables are skipped.
* Unlike a DataArray, there's no such thing as a consistent dimension order across variables in a Dataset. Probably best to use an `.isel` to deal with potentially transposed (x before y) variables?

**Comment by veenstrajelmer** [comment]
This would be great indeed!
